run:
  timeout: 5m
  build-tags:
    - linux

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - unconvert

issues:
  exclude-dirs:
    - bin
    - dist
    - config
    - charts
  exclude-rules:
    - path: zz_generated.deepcopy.go
      linters:
        - all

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
