"""Produces accuracy metrics (ROC/AUC, precision/recall, confusion matrix) for
the autoencoder threat-scoring pipeline against the synthetic labeled dataset
generated by generate_synthetic_dataset.py.

This is an evaluation utility for docs/paper-data — it is not part of the
production train/export/inference pipeline (scripts/train.py,
scripts/export_onnx.py, sentinel_ai/server.py) and intentionally holds out a
slice of "normal" samples the model never trains on, so the reported numbers
are not measuring memorization of the training set.

Run: python scripts/evaluate_model.py [--source synthetic|real]

--source real evaluates against scripts/build_real_dataset.py's real,
on-wire captures (docs/paper-data/real-dataset/) instead of the synthetic
generator — read that script's module docstring before trusting the
"anomalous" numbers from a --source real run: not every synthetic anomaly
type has an equally real production equivalent yet.
"""

from __future__ import annotations

import argparse
import json

import numpy as np
import torch

from scripts.build_real_dataset import _REAL_DATASET_DIR
from scripts.build_real_dataset import build as build_real
from scripts.generate_synthetic_dataset import generate as generate_synthetic
from sentinel_ai.model import Autoencoder, export_onnx, reconstruction_error, train
from sentinel_ai.server import ScoringEngine

# Mirrors pkg/controller.threat_score_watcher.go's BaseThreshold (0.85) and
# sensitivityMultiplier (high=0.8, medium=1.0, low=1.2), clamped to [0,1].
THRESHOLDS = {
    "high": 0.85 * 0.8,
    "medium": 0.85 * 1.0,
    "low": min(0.85 * 1.2, 1.0),
}


def confusion_at(scores: np.ndarray, labels: np.ndarray, threshold: float) -> dict:
    predicted_positive = scores >= threshold
    actual_positive = labels == 1

    tp = int(np.sum(predicted_positive & actual_positive))
    fp = int(np.sum(predicted_positive & ~actual_positive))
    tn = int(np.sum(~predicted_positive & ~actual_positive))
    fn = int(np.sum(~predicted_positive & actual_positive))

    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    fpr = fp / (fp + tn) if (fp + tn) else 0.0

    return {
        "threshold": threshold,
        "tp": tp,
        "fp": fp,
        "tn": tn,
        "fn": fn,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "false_positive_rate": fpr,
    }


def roc_points(scores: np.ndarray, labels: np.ndarray, num_thresholds: int = 200) -> list[dict]:
    points = []
    for t in np.linspace(0.0, 1.0, num_thresholds):
        c = confusion_at(scores, labels, float(t))
        points.append({"threshold": float(t), "fpr": c["false_positive_rate"], "tpr": c["recall"]})
    return points


def auc(points: list[dict]) -> float:
    # Sort by FPR ascending, trapezoidal rule. Thresholds sweep 1 -> 0 as
    # t goes 0 -> 1 in confusion_at's convention (score >= t), so FPR is
    # already monotonically non-decreasing as t decreases; sort defensively.
    pts = sorted(((p["fpr"], p["tpr"]) for p in points))
    area = 0.0
    for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
        area += (x1 - x0) * (y0 + y1) / 2.0
    return area


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        choices=["synthetic", "real"],
        default="synthetic",
        help="synthetic: scripts/generate_synthetic_dataset.py (default, reproducible, no live "
        "capture needed). real: scripts/build_real_dataset.py against docs/paper-data/"
        "real-dataset/ captures.",
    )
    args = parser.parse_args()

    if args.source == "real":
        normal, anomalous = build_real(_REAL_DATASET_DIR)
    else:
        normal, anomalous = generate_synthetic(num_normal=4000, num_anomalous=200, seed=42)

    rng = np.random.default_rng(42)
    idx = rng.permutation(len(normal))
    split = int(len(normal) * 0.8)
    train_idx, holdout_idx = idx[:split], idx[split:]
    normal_train, normal_holdout = normal[train_idx], normal[holdout_idx]

    model = Autoencoder(input_dim=normal.shape[1])
    torch.manual_seed(42)
    train(model, torch.from_numpy(normal_train), epochs=200, lr=1e-2)

    train_errors = reconstruction_error(model, torch.from_numpy(normal_train)).numpy()
    reference_error = float(np.percentile(train_errors, 99))

    model_path = f"models/eval_autoencoder_{args.source}.onnx"
    export_onnx(model, __import__("pathlib").Path(model_path), input_dim=normal.shape[1])
    __import__("pathlib").Path(f"models/eval_autoencoder_{args.source}.norm.json").write_text(
        json.dumps({"reference_error": reference_error})
    )

    engine = ScoringEngine(model_path)

    holdout_scores = np.array([engine.score_features(list(row)) for row in normal_holdout])
    anomalous_scores = np.array([engine.score_features(list(row)) for row in anomalous])

    scores = np.concatenate([holdout_scores, anomalous_scores])
    labels = np.concatenate([np.zeros(len(holdout_scores)), np.ones(len(anomalous_scores))])

    points = roc_points(scores, labels)
    area = auc(points)

    result = {
        "dataset": {
            "source": args.source,
            "normal_total": int(len(normal)),
            "normal_train": int(len(normal_train)),
            "normal_holdout": int(len(normal_holdout)),
            "anomalous": int(len(anomalous)),
            "seed": 42,
        },
        "score_summary": {
            "normal_holdout_mean": float(np.mean(holdout_scores)),
            "normal_holdout_p99": float(np.percentile(holdout_scores, 99)),
            "anomalous_mean": float(np.mean(anomalous_scores)),
            "anomalous_p1": float(np.percentile(anomalous_scores, 1)),
        },
        "auc": area,
        "confusion_by_sensitivity": {
            name: confusion_at(scores, labels, t) for name, t in THRESHOLDS.items()
        },
        "roc_sample": points[::20],  # thin the 200-point sweep for a readable table
    }
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
