import { Body, Controller, HttpCode, HttpStatus, Inject, Post } from '@nestjs/common';
import { Client } from 'pg';
import { generateUuid } from '@telecom-webhook/utils';
import { DATABASE_CLIENT } from '../infrastructure/database/database.module';

interface AutoWorkspaceRequest {
  /** UUID generated by the browser on first visit — stable per device. */
  token: string;
}

interface AutoWorkspaceResponse {
  workspaceId: string;
  endpointToken: string;
  name: string;
}

/**
 * WorkspaceController — public API for anonymous workspace provisioning.
 *
 * POST /workspace/auto
 *   Idempotent: if a workspace already exists for the given token it is
 *   returned unchanged. Otherwise a new one is created automatically.
 *   This is the core of the webhook.site-style UX — the browser generates a
 *   UUID once, stores it in localStorage, and always gets the same URL back.
 */
@Controller('workspace')
export class WorkspaceController {
  constructor(@Inject(DATABASE_CLIENT) private readonly db: Client) {}

  @Post('auto')
  @HttpCode(HttpStatus.OK)
  async auto(@Body() body: AutoWorkspaceRequest): Promise<AutoWorkspaceResponse> {
    // 1. Try to find an existing workspace for this token
    const existing = await this.db.query<{ id: string; name: string; endpoint_token: string }>(
      'SELECT id, name, endpoint_token FROM workspaces WHERE endpoint_token = $1',
      [body.token],
    );

    if (existing.rows.length > 0) {
      const row = existing.rows[0];
      return { workspaceId: row.id, endpointToken: row.endpoint_token, name: row.name };
    }

    // 2. Create new workspace
    const id = generateUuid();
    const name = `anon-${body.token.slice(0, 8)}`;

    await this.db.query(
      'INSERT INTO workspaces (id, name, endpoint_token) VALUES ($1, $2, $3)',
      [id, name, body.token],
    );

    return { workspaceId: id, endpointToken: body.token, name };
  }
}
