//go:build !ignore_autogenerated

// Code generated by hand to mirror controller-gen's object:deepcopy-gen output.
// This file MUST be kept in sync with telecomsecuritypolicy_types.go until
// controller-gen is wired into `make manifests` (see Makefile).

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.MatchLabels != nil {
		out.MatchLabels = make(map[string]string, len(in.MatchLabels))
		for key, val := range in.MatchLabels {
			out.MatchLabels[key] = val
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThreatDetectionSpec) DeepCopyInto(out *ThreatDetectionSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ThreatDetectionSpec.
func (in *ThreatDetectionSpec) DeepCopy() *ThreatDetectionSpec {
	if in == nil {
		return nil
	}
	out := new(ThreatDetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSpec) DeepCopyInto(out *ActionsSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ActionsSpec.
func (in *ActionsSpec) DeepCopy() *ActionsSpec {
	if in == nil {
		return nil
	}
	out := new(ActionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelecomSecurityPolicySpec) DeepCopyInto(out *TelecomSecurityPolicySpec) {
	*out = *in
	if in.TargetWorkloads != nil {
		l := make([]WorkloadSelector, len(in.TargetWorkloads))
		for i := range in.TargetWorkloads {
			in.TargetWorkloads[i].DeepCopyInto(&l[i])
		}
		out.TargetWorkloads = l
	}
	out.ThreatDetection = in.ThreatDetection
	out.Actions = in.Actions
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TelecomSecurityPolicySpec.
func (in *TelecomSecurityPolicySpec) DeepCopy() *TelecomSecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TelecomSecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelecomSecurityPolicyStatus) DeepCopyInto(out *TelecomSecurityPolicyStatus) {
	*out = *in
	if in.LastMitigationTime != nil {
		in, out := &in.LastMitigationTime, &out.LastMitigationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TelecomSecurityPolicyStatus.
func (in *TelecomSecurityPolicyStatus) DeepCopy() *TelecomSecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TelecomSecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelecomSecurityPolicy) DeepCopyInto(out *TelecomSecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TelecomSecurityPolicy.
func (in *TelecomSecurityPolicy) DeepCopy() *TelecomSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(TelecomSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelecomSecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelecomSecurityPolicyList) DeepCopyInto(out *TelecomSecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]TelecomSecurityPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new TelecomSecurityPolicyList.
func (in *TelecomSecurityPolicyList) DeepCopy() *TelecomSecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(TelecomSecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelecomSecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
